export default [
	{
		"icon":"https://icu.bet/theme/sp/assets/img/favicon-32x32.png",
		"link":"https://icu.bet/user"
	},
	{
		"icon":"https://woocloud.icu/favicon.ico",
		"link":"https://woocloud.icu/user"
	},
	{
		"icon":"https://18asmr.org/wp-content/uploads/2018/10/icon2.png",
		"link":"https://18asmr.org/"
	},
	{
		"icon":"https://fulijiejie.com/wp-content/uploads/2019/03/cropped-920f87b609c5466de5715f8ea4977bb9-270x270.png",
		"link":"https://ivsh.net/"
	},
	{
		"icon":"https://www.linovel.net/favicon.ico",
		"link":"https://www.linovel.net/"
	},
	{
		"icon":"https://www.tsdm.love/favicon.ico",
		"link":"https://www.tsdm.love/forum.php"
	},
	{
		"icon":"https://www.bilibili.com/favicon.ico",
		"link":"https://www.bilibili.com"
	},
]