export default [
	{
		"icon":"https://icu.bet/theme/sp/assets/img/favicon-32x32.png",
		"link":"https://icu.bet/user",
		"insteadicon":[
			"https://996icu.tv/wp-content/uploads/2018/10/icon2.png",
		],
		"insteadlink":[
			"https://996icu.tv/",
		],
	},
	{
		"icon":"https://woocloud.icu/favicon.ico",
		"link":"https://woocloud.icu/user"
	},
	{
		"icon":"https://18asmr.org/wp-content/uploads/2018/10/icon2.png",
		"link":"https://18asmr.org/",
		"insteadicon":[
			"http://18asmr.org/wp-content/uploads/2018/10/icon2.png",
		],
		"insteadlink":[
			"http://18asmr.org/",
		],
		"releaselink":"https://fljj.xyz/",
		"releaseicon":"https://fljj.xyz/icon.png"
	},
	{
		"link":"https://bodamuqiang.com/",
		"icon":"https://fulijiejie.com/wp-content/uploads/2019/03/cropped-920f87b609c5466de5715f8ea4977bb9-270x270.png",
		"insteadicon":[
			"https://fulijiejie.com/wp-content/uploads/2019/03/cropped-920f87b609c5466de5715f8ea4977bb9-270x270.png",
		],
		"insteadlink":[
			"https://fulijiejie.com/",
		]
	},
	{
		"icon":"https://www.linovel.net/favicon.ico",
		"link":"https://www.linovel.net/"
	},
	{
		"icon":"https://www.tsdm.live/favicon.ico",
		"link":"https://www.tsdm.live/forum.php"
	},
	{
		"icon":"https://www.bilibili.com/favicon.ico",
		"link":"https://www.bilibili.com"
	},
]