export default [
	{
		"icon":"https://www.996icu.tv/favicon.ico",
		"link":"https://www.996icu.tv",
		"insteadicon":[
			"https://www.t-v.me/favicon.ico",
		],
		"insteadlink":[
			"https://www.t-v.me",
		],
	},
	{
		"icon":"https://woocloud.icu/favicon.ico",
		"link":"https://woocloud.icu/user"
	},
	{
		"icon":"https://18asmr.org/wp-content/uploads/2018/10/icon2.png",
		"link":"https://18asmr.org/",
		"insteadicon":[
			"http://18asmr.org/wp-content/uploads/2018/10/icon2.png",
		],
		"insteadlink":[
			"http://18asmr.org/",
		]
	},
	{
		"link":"https://fulijiejie.com/",
		"icon":"https://fulijiejie.com/wp-content/uploads/2019/03/cropped-920f87b609c5466de5715f8ea4977bb9-270x270.png",
		"releaselink":"https://fljj.xyz/",
		"releaseicon":"https://fljj.xyz/icon.png"
	},
	{
		"icon":"https://www.linovel.net/favicon.ico",
		"link":"https://www.linovel.net/",
		"insteadicon":[
			"https://www.qingzhiwenku.com/favicon.ico",
		],
		"insteadlink":[
			"https://www.qingzhiwenku.com/",
		]
	},
	{
		"icon":"https://www.tsdm.live/favicon.ico",
		"link":"https://www.tsdm.live/forum.php"
	},
	{
		"icon":"https://www.bilibili.com/favicon.ico",
		"link":"https://www.bilibili.com"
	},
	{
		"icon":"https://acg.ge/wp-content/uploads/2019/02/a9610ae619331b6cc82d2138c882b8ed-192x192.jpg",
		"link":"https://acg.ge/"
	},
]